name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  DB_CONNECTION: mysql
  MYSQL_HOST: 127.0.0.1
  MYSQL_PORT: 8888
  MYSQL_USERNAME: root
  MYSQL_DBNAME: db_test
  MYSQL_PASSWORD: password
  MYSQL_ENGINE: InnoDB
  MYSQL_CHARSET: utf8mb4
  MYSQL_COLLATE: utf8mb4_unicode_ci
  API_KEY: 630239CC130E1A7FD81A27B140976EAF437D05B5
  COOKIE_SECRET_PASSWORD: 9B7UJszYjQ29K2LVOSM6zpOnBV459B7UJszYjQ29K2LVOSM6zpOnBV45
  COOKIE_TTL: 1800000
  COOKIE_IS_SECURE: false
  COOKIE_IS_HTTP_ONLY: false
  ALGOLIA_APPLICATION_ID: ZIWS65EYMJ
  ALGOLIA_ADMIN_API_KEY: ed25d2393118daed7c8f296107330ac6
  ALGOLIA_SEARCH_ONLY_API_KEY: e52ea6a37d010ab44711ba3b747096e5
  ALGOLIA_MIXED_CONTENT_INDEX: mixed_content
  RECOVERY_TOKEN_LIFE_TIME: 86400000
  BASE_URL: https://sgcares.com
  CACHE_REDIS_NAME: redisCache
  CACHE_REDIS_HOST: 127.0.0.1
  CACHE_REDIS_POST: 6379
  CACHE_REDIS_PREFIX: sgcares-cache
  PROXY_COUNT: 0
  IP_WHITELIST_PROXY_COUNT: 0
  SESSION_CACHE_NAME: redisCache
  SESSION_TTL: 172800000
  FIREBASE_DYNAMIC_LINK_API_KEY: JdfenfAdflajsdEIAO12312-B2o7KOPAJhQvQ9OA
  ANDROID_PACKAGE_NAME: some.android.package
  IOS_BUNDLE_ID: some.ios.bundle
  DYNAMIC_LINK_REDIRECT_URL: https://itunes.apple.com
  QR_CODE_IMAGE_TYPE: png
  GIVING_SG_API_KEY: 1wz811wz81hd35hhd35h
  GIVING_SG_API_URL: https://dev-api.giving.sg/v1/
  GIVING_SG_API_TIMEOUT: 10000
  GIVING_SG_FEED_STORY_PER_PAGE: 4
  GIVING_SG_FEED_ITEM_PER_PAGE: 7
  GIVING_SG_FEED_EXTERNAL_DATA_PER_PAGE: 1

jobs:
  build:
    strategy:
      matrix:
        node-version: [8.4.0]

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        ports:
          - 8888:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM
        run: npm install
      - run: echo $github
#       - name: Migrate Database
#         run: |
#           sudo service mysql start
#           mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS $MYSQL_DBNAME;'
#           npm run db:migrate:downall
#           npm run db:migrate:up
      - name: Build
        run: npm run build --if-present

      - name: Execute test
        run: npm test


      - name: Generate deployment package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Upload file
        uses: actions/upload-artifact@v1
        with:
          name: files
          path: deploy.zip

      - id: getShortSHA
        run: echo "::set-output name=result::${GITHUB_SHA::7}"

    outputs:
      shortSHA: ${{ steps.getShortSHA.outputs.result }}

  deploy:
    needs: [build]
    strategy:
      matrix:
        node-version: [8.4.0]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download file from step building
        uses: actions/download-artifact@v1
        with:
          name: files

      - name: Login AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - name: --STAGING-- Deploy to S3 & Elastic Beanstalk
        if: github.ref == 'refs/heads/develop'
        run: |
          aws s3 cp files/deploy.zip s3://$BUCKET_NAME/$FILE_NAME
          aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $VERSION_LABEL --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$FILE_NAME
          aws elasticbeanstalk update-environment --application-name $APPLICATION_NAME --environment-name $ENVIROMENT_NAME --version-label $VERSION_LABEL
        env:
          BUCKET_NAME: elasticbeanstalk-ap-southeast-1-381272808937
          VERSION_LABEL: devt_${{ needs.build.outputs.shortSHA }}
          FILE_NAME: devt_${{ needs.build.outputs.shortSHA }}.zip
          APPLICATION_NAME: SG Cares
          ENVIROMENT_NAME: SgCares-staging

      - name: --PRODUCTION-- Deploy to S3 & Elastic Beanstalk
        if: github.ref == 'refs/heads/master'
        run: |
          aws s3 cp files/deploy.zip s3://$BUCKET_NAME/$FILE_NAME
          aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $VERSION_LABEL --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$FILE_NAME
          aws elasticbeanstalk update-environment --application-name $APPLICATION_NAME --environment-name $ENVIROMENT_NAME --version-label $VERSION_LABEL
        env:
          BUCKET_NAME: elasticbeanstalk-ap-southeast-1-381272808937
          VERSION_LABEL: prod_${{ needs.build.outputs.shortSHA }}
          FILE_NAME: prod_${{ needs.build.outputs.shortSHA }}.zip
          APPLICATION_NAME: "SG Cares"
          ENVIROMENT_NAME: SgCares-production

      - name: Deployed successfully!
        run: echo App deployed to ELB
