# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    
jobs:
  build:
    strategy:
      matrix:
        node-version: [8]

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Prepare env
        run: |
          cp .env.staging.ci .env

      - run: npm run build --if-present
      - run: npm test

      - name: Generate deployment package
      - run: zip -r deploy.zip * -x "**node_modules**"

      - name: Upload file
        uses: actions/upload-artifact@v1
        with:
          name: deploy_file
          path: deploy.zip
        
